# Generated by Django 4.0.4 on 2022-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cty', models.CharField(max_length=26)),
                ('cq', models.CharField(blank=True, max_length=5, null=True)),
                ('itu', models.CharField(blank=True, max_length=5, null=True)),
                ('cont', models.CharField(blank=True, max_length=5, null=True)),
                ('lat', models.CharField(blank=True, max_length=9, null=True)),
                ('lon', models.CharField(blank=True, max_length=10, null=True)),
                ('loctime', models.CharField(blank=True, max_length=9, null=True)),
                ('dxcc', models.CharField(blank=True, max_length=6, null=True)),
                ('pref', models.CharField(blank=True, max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=20)),
                ('band', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-band', '-datetime'),
            },
        ),
    ]
